# Generated by Django 3.0 on 2021-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ممثل المؤسسة'), (2, 'حساب فرد')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
